export const  GET_ADMIN_DATA_REQUEST = "GET_ADMIN_DATA_REQUEST";
export const  GET_ADMIN_DATA_FAILURE = "GET_ADMIN_DATA_FAILURE";
export const  GET_ADMIN_DATA_SUCCESS = "GET_ADMIN_DATA_SUCCESS";

export const  DELETE_ADMIN_DATA_REQUEST = "DELETE_ADMIN_DATA_REQUEST";
export const  DELETE_ADMIN_DATA_FAILURE = "DELETE_ADMIN_DATA_FAILURE";
export const  DELETE_ADMIN_DATA_SUCCESS = "DELETE_ADMIN_DATA_SUCCESS";

export const  POST_ADMIN_DATA_REQUEST = "POST_ADMIN_DATA_REQUEST";
export const  POST_ADMIN_DATA_FAILURE = "POST_ADMIN_DATA_FAILURE";
export const  POST_ADMIN_DATA_SUCCESS = "POST_ADMIN_DATA_SUCCESS";

export const  EDIT_ADMIN_DATA_REQUEST = "EDIT_ADMIN_DATA_REQUEST";
export const  EDIT_ADMIN_DATA_FAILURE = "EDIT_ADMIN_DATA_FAILURE";
export const  EDIT_ADMIN_DATA_SUCCESS = "EDIT_ADMIN_DATA_SUCCESS";